apiVersion: v1
kind: Service
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: tcp
  selector:
     app: drupal
  type: ClusterIP  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  selector:
    matchLabels:
      app: drupal
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          image: drupal:8-apache
          imagePullPolicy: Always
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - name: tcp-api
              containerPort: 80
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_DATABASE
              value: drupal
            - name: MYSQL_USER
              value: drupal_user
            - name: MYSQL_PASSWORD
              value: drupal_database_password                                    