version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    #ports:
    #  - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal_user
      MYSQL_PASSWORD: drupal_database_password
  drupal:
    image: drupal:8-apache
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "drupal"
      MYSQL_USER: "drupal_user"
      MYSQL_PASSWORD: "drupal_database_password"
    command: --default-authentication-plugin=mysql_native_password