apiVersion: v1
kind: Secret
metadata:
    name: mysql-credentials
    labels:
        app.kubernetes.io/name: mysql-credentials
        app.kubernetes.io/instance: mysql-credentials
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: config
        app.kubernetes.io/part-of: customers
        app.kubernetes.io/managed-by: helm 
type: Opaque
data:
    #password
    #lab01user
    #lab01userpwd
    root_password: cGFzc3dvcmQ=
    db_user: bGFiMDF1c2Vy
    db_pwd: bGFiMDF1c2VycHdk