apiVersion: v1
kind: Service
metadata:
  name: web01
  labels:
    app: web01
spec:
  ports:
    - name: http-api
      port: 9060
      targetPort: 80
      nodePort: 30003
      protocol: TCP
  selector:
    app: web01
  type: NodePort