apiVersion: v1
kind: Secret
metadata:
    name: git-credentials
    labels:
        app.kubernetes.io/name: common
        app.kubernetes.io/instance: git-credentials
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: config
        app.kubernetes.io/part-of: common
        app.kubernetes.io/managed-by: helm 
type: Opaque
data:
    username: "bXplZ2FycmFAZ21haWwuY29t"
    password: "LkhUUk5OQllxdyFFeWkhaGtZcl80VEpDV000NDM5"