version: '3.8'
services:
  backend:
      image: wslph/mule:3.9.0-ee
      container_name: mule-ee
      restart: always
      ports:
        - 7777:7777
        - 1098:1098
        - 25000:25000
        - 8081:8081
      environment:
        MULE_ESB_NAME: 'My-ESB-Server-01'
        MULE_MMC_AGENT_PORT: 7777
        #MULE_MMC_URL: "http://localhost/mmc-console"
        MULE_MMC_USERNAME: "admin"
        MULE_MMC_PASSWORD: "admin"
        MULE_MMC_AGENT_HOST: "123.455.234.110"
