apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: USER_ADMIN
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: USER_PWD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  restartPolicy: Never
