apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config-5
              key: special.how
        - name: LIVES
          valueFrom:
            configMapKeyRef:
              name: app-config-4
              key: lives
  restartPolicy: Never
