@SERVER=http://localhost:8080
//@SERVER=https://localhost:5001

### LIST

GET {{SERVER}}/health HTTP/1.1

### LIST

GET {{SERVER}}/Customer HTTP/1.1

### Create customer
POST {{SERVER}}/Customer HTTP/1.1
content-type: application/json

{
	"FirstName": "Juan",
	"LastName": "Perez1"
}

### DELETE customer
DELETE {{SERVER}}/5ffb072f3f53f6369748780e HTTP/1.1


