apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
      app.kubernetes.io/name: db
      app.kubernetes.io/instance: db
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/component: storage
      app.kubernetes.io/part-of: customers
      app.kubernetes.io/managed-by: helm 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi